import { Recipe } from "@/types/recipe"
export const FAKE_RECIPES: Recipe[] = [{
    id: "1",
    name: "Classic Pancakes",
    description: "Fluffy pancakes perfect for a weekend breakfast",
    ingredients: [
      { name: "all-purpose flour", quantity: 2, unit: "cups" },
      { name: "sugar", quantity: 2, unit: "tbsp" },
      { name: "baking powder", quantity: 2, unit: "tsp" },
      { name: "salt", quantity: 0.5, unit: "tsp" },
      { name: "milk", quantity: 1.5, unit: "cups" },
      { name: "eggs", quantity: 2, unit: "large" },
      { name: "butter", quantity: 2, unit: "tbsp" },
    ],
    mealTypes: new Set(["breakfast"]),
  },
  {
    id: "2",
    name: "Chicken Caesar Salad",
    description: "A refreshing salad with grilled chicken and homemade dressing",
    ingredients: [
      { name: "romaine lettuce", quantity: 1, unit: "head" },
      { name: "chicken breast", quantity: 2, unit: "pieces" },
      { name: "parmesan cheese", quantity: 0.5, unit: "cup" },
      { name: "croutons", quantity: 1, unit: "cup" },
      { name: "caesar dressing", quantity: 0.25, unit: "cup" },
    ],
    mealTypes: new Set(["lunch", "dinner"]),
  },
  {
    id: "3",
    name: "Spaghetti Bolognese",
    description: "Classic Italian pasta with rich meat sauce",
    ingredients: [
      { name: "spaghetti", quantity: 1, unit: "pound" },
      { name: "ground beef", quantity: 1, unit: "pound" },
      { name: "onion", quantity: 1, unit: "medium" },
      { name: "garlic", quantity: 3, unit: "cloves" },
      { name: "tomato sauce", quantity: 2, unit: "cups" },
      { name: "tomato paste", quantity: 2, unit: "tbsp" },
      { name: "dried oregano", quantity: 1, unit: "tsp" },
      { name: "dried basil", quantity: 1, unit: "tsp" },
    ],
    mealTypes: new Set(["dinner"]),
  },]
